### ISSUE TITLE
Mod doesn't load up

### ISSUE THREAD

**Issue by pctillotson1** [team-abnormals/buzzier-bees#10]
My _Minecraft_ doesn't seem to notice _Buzzier Bees_ at all.  The recipes don't work, there's no creative tab for it, and I can't cheat in items from it like I can items from other mods.

Yeah, most other fabric mods work fine.  I've noticed most of them (except _Snow! Real Magic!_, which also doesn't work) have a file called fabric.mod.json but this one doesn't.  After I made that connection, I tried to copy a working fabric.mod.json file from another mod and change the filepaths.  That made Minecraft crash instead of simply ignoring _Buzzier Bees_, probably because it actually tried to load it up but I guessed wrong about what to tell it.

**Comment by bageldotjpg** [comment]
1) The mod doesn't have a creative tab
2) This is a forge mod

**Comment by pctillotson1** [comment]
Ah, thanks.  It was 1.15 so I assumed.  Sorry.  (The other one Minecraft wasn't noticing is also Forge, and I didn't notice that either.)  Feeling pretty dumb right now.
