### ISSUE TITLE
Unable to join LAN world after (both Host and Guest) updating mod to 2.1.0

### ISSUE THREAD

**Issue by mpohjola** [team-abnormals/buzzier-bees#102]
We have a 1.16.1 LAN world which was running Buzzier Bees 2.0.0

After both Host (one running the world) and Guest (me trying to join it) updated the Buzzier Bees to 2.1.0 (and Abnormals Core to 2.0.7) the world correctly opens for the Host but the Guest is unable to join the world. The following error message is found from the Guest's Log:

[01Nov2020 12:23:12.105] [Render thread/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	buzzier_bees:columbine_scented_candle: 836

[01Nov2020 12:23:12.106] [Render thread/ERROR] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Missing registry data for network connection:
	minecraft:block: buzzier_bees:columbine_scented_candle

------

Attempting to downgrade the mod back to 2.0.0 causes similar error messages to appear (for different registry entries). For reference after we downgraded the mod back to 2.0.0 the following error occurred:

[01Nov2020 14:06:08.921] [Render thread/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	buzzier_bees:red_lotus_flower_scented_candle: 1596
	buzzier_bees:white_lotus_flower_scented_candle: 1594
	buzzier_bees:chiseled_honeycomb_bricks: 1595

[01Nov2020 14:06:08.923] [Render thread/ERROR] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Missing registry data for network connection:
	minecraft:block: buzzier_bees:white_lotus_flower_scented_candle
	minecraft:block: buzzier_bees:chiseled_honeycomb_bricks
	minecraft:block: buzzier_bees:red_lotus_flower_scented_candle

----

As such we are unable to continue playing the LAN world with either the newer version or older version of the mod and are also afraid that removing the mod altogether will break the world as well (as we have used quite a lot of the mod's new blocks etc).

We also tried different Forge versions (we were on version 32.0.106 before mod update, but have also tried 32.0.107 and 32.0.108), so far none of them have helped to resolve the issue.

Provided a full Guest log as reference. I can get the Host logs as well if needed.

[minecraft-log-2020-11-01.txt](https://github.com/minecraftabnormals/Buzzier-Bees/files/5470823/minecraft-log-2020-11-01.txt)

I will continue my own debugging and attempts to get things working again, (and will provide an update if I figure out what is causing the issues or if I find a way around them) and would love to get the issue resolved.

**Comment by bageldotjpg** [comment]
Looks to be Forge not handling missing registry data properly... unfortunately I don't have a fix.
I do think they fixed this on 1.16.2+ so hopefully when we port it will work fine then.

**Comment by hron84** [comment]
@bageldotjpg do you plan to upgrade to 1.16.2+ or you stopped work on this mod?

**Comment by bageldotjpg** [comment]
> I do think they fixed this on 1.16.2+ so hopefully when we port it will work fine then.
