### ISSUE TITLE
Bug with the hitbox 

### ISSUE THREAD

**Issue by DrWhite01** [team-abnormals/buzzier-bees#106]
For some reason it won't let me upload the image so here is a discord link:

https://cdn.discordapp.com/attachments/154261184701267969/782024323748724756/2020-11-27_20.19.37.png

Basically the problem is that when I look at the block the lines that select it become transparent and I can see through it.

**Comment by bageldotjpg** [comment]
Unfortunately this is a bug with rendering in Forge
It can be fixed using fabulous graphics but I'm afraid thats all that can be done
