### ISSUE TITLE
Suggestion: Config option to disable buttercup particles

### ISSUE THREAD

**Issue by GrantGryczan** [team-abnormals/buzzier-bees#115]
The buttercup particles are very obtrusive in the flower forest biome. It fills the air with what looks like streams of pollen, which somewhat cancels the peaceful aesthetic of the biome, since buttercups are everywhere. A config option to disable it would be useful.

I did try to make a resource pack that makes the particles transparent, but it seems to be incompatible with OptiFine (it shows short, thin, vertical white lines that flash in random places above the buttercup for single frames), which is a must-have mod for me.

**Comment by bageldotjpg** [comment]
I believe there was a very large discord debate about this and why it won't happen
And I'd recommend dropping optifine, you'll just encounter more mod issues as you use it.
