### ISSUE TITLE
Bonemeal Flower Duplication Works on Botania Flowers

### ISSUE THREAD

**Issue by Noobulus** [team-abnormals/buzzier-bees#127]
The problem is as the name states: the bonemeal-based flower duplication added by Buzzier Bees allows for duplication of every flower in Botania, short of regular mystical flowers and shimmering mushrooms. This works on both 1.15 and 1.16. I'd imagine that this also works on any other modded item that extends whatever flower class (object?) Botania's flowers do.

For a fix, I'd suggest a blacklist of flowers (or flower-like objects) that aren't allowed to be duplicated by this feature, adjustable in the config for pack makers.

**Comment by bageldotjpg** [comment]
There is a blacklist, its a tag called `buzzier_bees:flower_blacklist`

**Comment by elucent** [comment]
Would it be possible to preclude any flower that has a tile entity by default? That seems like a pretty good heuristic. The tag is helpful, but for a mod like Botania, expecting pack authors to extend the tag themselves with dozens of new entries seems excessive. Especially when it's just to fix what is essentially a dupe bug.
