### ISSUE TITLE
Apiarist bug/oversight/wack

### ISSUE THREAD

**Issue by ouravantgarde** [team-abnormals/buzzier-bees#133]
I don't know the code that the apiarist uses, but I assume that the apiarist checks for items with the forge:flower tag for its flower trades.

However, not all flowers are obtainable. For example, recently on the SMP an apiarist was buying Tall Yucca Flowers, which can't be obtained to my knowledge. Tall yucca flowers can only be grown. Breaking the flower, shears or not, yields 2 yucca flowers.

As for how you would fix this... :damn:

There isn't really an unobtainable tag to my knowledge. You *could* just make an if/this unless/that list that excludes flowers such as Tall Yucca Flowers, which would solve problems within our inner circle of mods, but doesn't solve the actual problem and can create potential incompatibility.

**Comment by MarioSMB** [comment]
Perhaps it would be best to only make use of the `minecraft:small_flowers` tag?
