### ISSUE TITLE
[1.16.5] Apiarist structure error

### ISSUE THREAD

**Issue by Not-February** [team-abnormals/buzzier-bees#134]
The mod Blame caught this in the logs while the world was loading.

`Forge 36.1.4`
`buzzier_bees-1.16.5-3.0.1`

> [04/12/2021 04:13:38 pm]: ****************** Blame Report 1.9.2 ******************
> [04/12/2021 04:13:38 pm]: Failed to load structure nbt file from: buzzier_bees:village/apiarist_bees/bees_1
> [04/12/2021 04:13:38 pm]: The path represented by this is: data/buzzier_bees/structures/village/apiarist_bees/bees_1.nbt
> [04/12/2021 04:13:38 pm]: The calling Template Pool is: buzzier_bees:village/apiarist_bees
> [04/12/2021 04:13:38 pm]: Most common cause is that there is a typo in this path to the nbt file.
> [04/12/2021 04:13:38 pm]: Please let the mod author know about this so they can double check to make sure the path is correct.
> [04/12/2021 04:13:38 pm]: A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

**Comment by TheVillain-Inc** [comment]
~~So I'm not sure if this is the same bug that I'm having - but the Apiarist hut is causing world corruption.~~

~~Still testing, I think its a compat issue but not sure which mod.~~

~~Attempting to gen a chunk that contains an Apiarist Hut fails, no obvious error in log, game still runs but no further chunks are loaded, player cannot interact with blocks, blocks broken drop nothing, items dropped 'vanish', all entities are frozen in place.~~ 

~~Game crashes on attempt to save and exit or force quit.~~

~~Removing Buzzier Bees and reloading save causes village to gen normally~~

*UPDATE*

Realistic Bees is the conflict. Odd but there you go. Have notified them. 
Creating a new Issue.
