### ISSUE TITLE
Flower duplication blacklist

### ISSUE THREAD

**Issue by AlexProGear** [team-abnormals/buzzier-bees#140]
The flower duplication mechanic really should not be possible with Botania flowers.
But it is.
Can you please add the blacklist in config file for such cases?

**Comment by Hubry** [comment]
The flower tag already has the flowers in it...
https://github.com/team-abnormals/buzzier-bees/blob/c85106c67140de6351d69509608eccf750b5caaf/src/main/resources/data/buzzier_bees/tags/blocks/flower_blacklist.json#L6-L9
...which is the old Forge-added syntax, which was dropped once Mojang actually added their own optional tag item syntax 
([example of it](https://github.com/Vazkii/Botania/blob/fa025892796ffbb3583cf48b09833537c740ed54/src/generated/resources/data/botania/tags/entity_types/cocoon/common_aquatic.json))

**Comment by bageldotjpg** [comment]
Should be fixed in 404a477558beee4d2a1518d50a09fad92f7124f6
