### ISSUE TITLE
Candle Recipe compatability with Quark/Supplementaries

### ISSUE THREAD

**Issue by plunginghornets** [team-abnormals/buzzier-bees#141]
This mod removes all recipes for quark's own candles. I understand this in terms of balancing and removing clutter, but it has an unintended side effect with the mod [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries). Supplementaries has a Candelabra item that takes three candles as ingredients. It accepts any quark candle, and I would guess you can see the problem here.

I am also going to post on the [Supplementaries issues page](https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/71) to suggest they add compatibility with your mod, but perhaps you could add a config option to re-enable quark candles or just re-enable it if the mod detects supplementaries is installed.

**Comment by bageldotjpg** [comment]
From your report, it seems Supplementaries is fixing this.
Also Quark disables the candles on their end, we do not do that.
