### ISSUE TITLE
Baby bees suffocate when touching underside of block

### ISSUE THREAD

**Issue by Awesomespore** [team-abnormals/buzzier-bees#147]
Just saw a baby bee press against the underside of spruce planks and suffocate (the bee did nothing to avoid or stop this lmao)
Guessing it's due to the hitbox size or something

**Comment by hron84** [comment]
Yeah, it's a vanilla bug. Does not belong this mod.

**Comment by Awesomespore** [comment]
Mmm, guess I should just close this issue, eh?
