### ISSUE TITLE
Bee duplication with Bee in a Bottle and Realistic Bees

### ISSUE THREAD

**Issue by James103** [team-abnormals/buzzier-bees#152]
## Information
Minecraft version: 1.16.5
Forge version: 36.2.2
Buzzier Bees 1.16.5 - 3.0.1
[Realistic Bees](https://minecraft.natamus.com/realistic-bees/) 1.5
Environment: Singleplayer and Multiplayer
Originally reported in https://github.com/ricksouth/serilum-mc-mods/issues/657

## The bug
When Buzzier Bees is used in conjunction with Realistic Bees, releasing a bee from a Bee in a Bottle causes Realistic Bees to spawn 4 more bees where the bee was released at.

To try a work around this bug, in the bee spawn that occurs as a result of using a Bee in a Bottle, add the following line of code:
```java
bee.addTag("realisticbees.ignorebee");
```
NOTE: If adding in the line inside the `if (entity instanceof BeeEntity) { ... }` block does not prevent the bug, the following lines will need to be refactored so that the tag can be added before the entity can be spawned into the world:
https://github.com/team-abnormals/buzzier-bees/blob/ba5f13416be8b1e6e6195fc7e719d4298362c63d/src/main/java/com/minecraftabnormals/buzzier_bees/common/items/BeeBottleItem.java#L59-L79

**Comment by bageldotjpg** [comment]
This seems like something that should be fixed on Realistic Bees' end, because it could cause issues for just about any mod that spawns bees for something. Realistic Bees should instead check the SpawnReason when a bee is spawned to make sure it is natural rather than duplicating all bee spawns.
