### ISSUE TITLE
Honey Slime crash

### ISSUE THREAD

**Issue by StellaBiscuit** [team-abnormals/buzzier-bees#17]
Using Optifine, the honey slime crash the game at starting

[crash-2020-02-17_19.46.51-client.txt](https://github.com/bageldotjpg/BuzzierBees/files/4216864/crash-2020-02-17_19.46.51-client.txt)

**Comment by bageldotjpg** [comment]
Yeah. Nothing I can do about this. Optifine does not play well with mods, especially brand new version of optifine that aren't even complete yet. Sorry.
