### ISSUE TITLE
[Suggestion] Candles on Lily Pads

### ISSUE THREAD

**Issue by Matthysse** [team-abnormals/buzzier-bees#21]
Hello!
Just a little feature request : add the ability to put candles on lily pads. Maybe with a crafting recipe or on right click on a lily pad with a candle in hand. I would create lovely decoration for parks for example!

**Comment by bageldotjpg** [comment]
Would be nice but would be quite a lot of extra blockstates and models and properties. Maybe I'll reconsider in the future
