### ISSUE TITLE
[Suggestion] Remove the Flower Forest check from Honey Slime spawning condition

### ISSUE THREAD

**Issue by TelepathicGrunt** [team-abnormals/buzzier-bees#22]
I have a mod that is trying to import other mod's naturally spawning entities and I noticed that BuzzierBees's Honey Slime mob will not spawn in the new biome. After taking a look at the code, I see that the spawn condition for the slime has a hardcoded check for Flower Forest biomes only.
https://github.com/bageldotjpg/BuzzierBees/blob/42336f0456381e5dc6faad8ad16b460c19bcbd20/src/main/java/com/bagel/buzzierbees/common/entities/HoneySlimeEntity.java#L245

My suggestion is to remove that check as you already are adding the Honey Slime mob to just the Flower Forest which makes checking for the Flower Forest biome a bit redundant and hurts mod compatibility a bit.
https://github.com/bageldotjpg/BuzzierBees/blob/42336f0456381e5dc6faad8ad16b460c19bcbd20/src/main/java/com/bagel/buzzierbees/core/registry/BBEntities.java#L53

I hope this suggestion helps. :)

**Comment by bageldotjpg** [comment]
Will do, thanks!
