### ISSUE TITLE
Crash with WorldBlender

### ISSUE THREAD

**Issue by Shadows-of-Fire** [team-abnormals/buzzier-bees#23]
It would appear you aren't registering your `Feature`s, as they do not have registry names.

This causes WorldBlender to crash when attempting to retrieve them: https://github.com/TelepathicGrunt/WorldBlender/issues/2

**Comment by bageldotjpg** [comment]
Is this still occuring?

**Comment by Shadows-of-Fire** [comment]
I doubt it, as worldblender put in a bandaid on their end.  If you still aren't registering your features, you should go do that.
