### ISSUE TITLE
Can't get Honey Brick Wall from stonecutting

### ISSUE THREAD

**Issue by BKthousand** [team-abnormals/buzzier-bees#34]
When putting some Honey Bricks into the stonecutter, you get a slab and two stairs options, instead of a wall option as well.
![honey_bricks_stonecutting](https://user-images.githubusercontent.com/28869185/79056998-79efb280-7c19-11ea-8191-3f332bd2695c.png)

**Comment by bageldotjpg** [comment]
Fixed for next release
