### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by kwerin** [team-abnormals/buzzier-bees#35]
When I check the log file when starting Minecraft with Buzzier Bees 1.4, Forge 31.1.43 I get this line near the top:

[org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 10:99 token recognition error at: ';'

When I remove Buzzier Bees the line no longer appears.

No idea if this is causing any gameplay issues.

**Comment by bageldotjpg** [comment]
Not sure what it is but it isn't causing any issues
