### ISSUE TITLE
(Suggestion )(1.15.2) Make it so that crouching in midair and landing on Crystallized Honey Block will not break the block.

### ISSUE THREAD

**Issue by TelepathicGrunt** [team-abnormals/buzzier-bees#36]
I was testing out making the entire land covered in this block and I realized that getting around is fairly difficult as the block breaks super easily if the player doesn't land barely on its edges.

I was wondering if making it so that if you crouch in midair and land on the block, that the block doesn't break like you tried to land carefully. If this isn't what you want, that's ok! It's just a suggestion I think would be nice. :)

**Comment by bageldotjpg** [comment]
It is intended to be a super fragile block, might revisit later
