### ISSUE TITLE
Dropped  candles saved when unloading chunk causes would to hang when reloading chunk

### ISSUE THREAD

**Issue by TelepathicGrunt** [team-abnormals/buzzier-bees#45]
To recreate this bug, ~~go into any world, fly up super high, and place candles on the side of a block so the candles have a long way down to fall. Exit the world while the candle is falling in midair. Then re-enter the world and the game will hang forever.~~ EDIT: It's not falling candles but simply dropped candles that triggers this bug. Drop a few candles on the ground, exit, and re-enter for the world to hang forever.

The hand seems to be caused by this line of code.
<https://github.com/bageldotjpg/Buzzier-Bees/blob/e15a70118eec7f2ab062f5304a7d385dae98e0c2/src/main/java/com/bagel/buzzierbees/core/registry/BBEvents.java#L69-L73>

Specifically, it hang at getEntitiesWithinAABB for some reason as if the chunk isn't ready yet and will never be ready. Really weird.

Here's what the thread that gets stuck looks like: 
![image](https://user-images.githubusercontent.com/40846040/80925851-452ad300-8d61-11ea-9bf7-bb287d93a12b.png)

Hopefully this won't be too bad to fix!

**Comment by bageldotjpg** [comment]
"Fixed" in #45 by not making candles fall. Might revisit eventually.
