### ISSUE TITLE
Documentation: Images view isn't visible in Launcher

### ISSUE THREAD

**Issue by GeorgeWL** [team-abnormals/buzzier-bees#65]
I'm using GD Launcher, but I've also tested this in twitch launcher.

All the documentation for this mod seems to be on the images tab on the curseforge page.

But unfortunately, if you're trying to view the mod information from inside of one of those aforementioned launchers, the curseforge API only returns the mod description, so one cannot see the images at all.

Could you possibly put more detail into the description tab on curseforge please?

Even just a link to the images tab saying something like `[Details Here] (link)` would be nice

**Comment by bageldotjpg** [comment]
The wiki is a work in progress. In the mean time, you can take two seconds and open the images page on a internet browser of your choice.

**Comment by GeorgeWL** [comment]
Surely adding a subtle link into the description, literally a one-line change, would be okay still?

Due to most mods not using the images tab at all and having everything in the description, until I asked around I didn't even know that was where it was.

Just as a nicety for dumbos like me.

**Comment by bageldotjpg** [comment]
You not realizing the images tab exists on the curseforge website is not my fault. I’m not linking it when it appears directly next to it on Curseforge. Many mods utilize that page

**Comment by GeorgeWL** [comment]
It's a one line change.

Less than a line.

**Comment by bageldotjpg** [comment]
It’s literally directly next to it on the curse page. Why would I link something that is directly next to it on the website? How lazy are you?
