### ISSUE TITLE
Documentation: Curseforge Details

### ISSUE THREAD

**Issue by GeorgeWL** [team-abnormals/buzzier-bees#66]
I'm using GD Launcher, but I've also tested this in twitch launcher.

All the documentation for this mod seems to be on the images tab on the curseforge page.

But unfortunately, if you're trying to view the mod information from inside of one of those aforementioned launchers, the curseforge API only returns the mod description, so one cannot see the images at all.

Could you possibly put more detail into the description tab on curseforge please?

Even just a link to the images tab saying something like `[Details Here] (link)` would be nice

Many people don't even know the website exists, and just download a launcher then get mods from there. If you can make things easier for people, it costs you nothing

**Comment by bageldotjpg** [comment]
Lol do you think this will get me to do it? Click yourself over to the curseforge page and click images, or just open the mod and see what it has
