### ISSUE TITLE
buzzier bees 1.16.1 issue

### ISSUE THREAD

**Issue by Elyo420** [team-abnormals/buzzier-bees#72]
Hi, i recently downloaded the new 1.16 version for buzzier bees, a mod wich i love, but it was missing the new flowers, as well as the new planks and all wood variants (door, fences boat, etc) is that a bug? or did you removed it all? thanks.
pd: the honey slime was missing as well but i honeystly don't care about it :)

**Comment by bageldotjpg** [comment]
![image](https://user-images.githubusercontent.com/55970498/88242517-07986080-cc53-11ea-97ae-29540c5b43be.png)
A lot of the content I was not happy with was removed. The flowers will be returning at a later time
