### ISSUE TITLE
Mod crashes on world load when Quark and JEI are installed

### ISSUE THREAD

**Issue by ex0planetary** [team-abnormals/buzzier-bees#73]
Basically what it says on the tin. Here's the crash report:
[Crash Report](https://pastebin.com/NVgru105)
Not sure which mod's end this is on so if it's not because of Buzzier Bees just let me know and I'll send this to one of the other mods. I've confirmed that all three mods need to be present for the crash.

**Comment by bageldotjpg** [comment]
I think this has been fixed in the latest Quark release

**Comment by ex0planetary** [comment]
Can confirm it has, guess it was on Quark's end then
