### ISSUE TITLE
Resource Packs don't change Beehive textures

### ISSUE THREAD

**Issue by Halyo-Alex** [team-abnormals/buzzier-bees#83]
Pretty much exactly what the title says; I tried making a resource pack that recolors Crimson and Warped woods and wanted to include the beehives of those woods from this mod; I set up the folder path correctly to my knowledge, and it doesn't work. Maybe I'm missing something, but I don't see what it is.

**Comment by bageldotjpg** [comment]
There's no reason it wouldn't be working. Ensure the path is correct and that the resource pack is loaded in the game and its above the Mod Resources pack.

**Comment by Halyo-Alex** [comment]
...That's the issue. I am doing all of that, and it isn't working. I'll gladly take a correction on what folder path I need; I just want this to work and it isn't.

**Comment by bageldotjpg** [comment]
You can check the correct path on this repository. I just tested it and it worked just fine

**Comment by Halyo-Alex** [comment]
Huh. Well okay, I'll see. Thanks!

**Comment by bageldotjpg** [comment]
No prob

**Comment by Halyo-Alex** [comment]
OH MY GOD I AM AN IDIOT.

I was putting the textures into the wrong version of the resource pack; one that was not loaded.

Thanks for putting up with my stupidity. Sorry to bother you.

**Comment by bageldotjpg** [comment]
Lol, no worries
