### ISSUE TITLE
Eating honey food crashes the game

### ISSUE THREAD

**Issue by WitheredWasabi** [team-abnormals/buzzier-bees#95]

**Comment by bageldotjpg** [comment]
provide crash report

**Comment by WitheredWasabi** [comment]
[crash-2020-10-12_22.19.51-server.txt](https://github.com/minecraftabnormals/Buzzier-Bees/files/5369092/crash-2020-10-12_22.19.51-server.txt)
dear bagel

**Comment by bageldotjpg** [comment]
lmao bruv why you using cave upgrade borked ass nae nae ass weak ass dead ass broke ass cringe ass cave ass irrelevant ass mod

**Comment by WitheredWasabi** [comment]
bruh   . . .                      ✋😔
